apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: bank-service
  namespace: default
spec:
  selector:
    matchLabels:
      app: bank-service
    endpoints:
      - port: http
        path: /metrics
        interval: 15s