apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: bank-service
  template:
    metadata:
      labels:
        app: bank-service
    spec:
      containers:
        - name: bank-service-api
          image: bank-service:1.0
          imagePullPolicy: ifNotPresent
          ports:
            - containerPort: 8000
          startupProbe:
            httpGet: {path: /health, port: 8000}
            failureThreshold: 3
            periodSeconds: 2
          livenessProbe:
            httpGet: {path: /health, port: 8000}
            periodSeconds: 5
          readinessProbe:
            httpGet: {path: /health, port: 8000}
            periodSeconds: 5
          resources:
            requests: {cpu: 100m, memory: 128Mi}
            limits: {cpu: 500m, memory: 256Mi}


    